### ISSUE TITLE
Robot Additive Manufacturing

### ISSUE THREAD

**Issue by moorjuli** [zhangty019/MultiAxis_3DP_MotionPlanning#1]
Hey,

I would like to use this project, or its integration in S^3 Slicer, to produce parts using a universal robot, similar to your presentation video. The G code that this software outputs seems to be generated for a 5-axis cnc setup with a rotating table, as also visible in the simulation. Is there an easy option to produce 6-axis robot gcode (x,y,z,rx,ry,rz) with this? Similar to the toolpath coordinates generated for example by ReinforcedFDM, which are used as input here? I was able to modify the source code so that the x,y,z works for me, but i struggle to get the head rotation right. Thanks for any help

**Comment by zhangty019** [comment]
This project focuses on the 5-axis CNC printing, the motion planning algorithm and Gcode generation are used only for CNC printing. For robot printing,  we use the RoboDK to help us generate the code for UR5 control.

**Comment by moorjuli** [comment]
Thank you for your quick reply!
