### ISSUE TITLE
how to generate gcode for a six-axis robot

### ISSUE THREAD

**Issue by yubeilin** [zhangty019/MultiAxis_3DP_MotionPlanning#2]
Hey, I wonder how to integrate this project with RoboDK software to generate gcode for a six-axis robot. Do you create the surface in RoboDK or import the planned path into RoboDK, or is there another way? I hope you can help me, thank you.

**Comment by zhangty019** [comment]
Hi, this project is mainly used for tilting table-based CNC printing. As for the robot printing setup, please check this project in my repository (https://github.com/zhangty019/Support_Generation_for_Curved_RoboFDM). There is a hardware platform to show how to use the UR robot to do 3D printing.

**Comment by yubeilin** [comment]
Thank you very much for your help, your research is fantastic!
